const icons={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',ledger:'M6 3h12v18l-3-2-3 2-3-2-3 2ZM9 8h6M9 12h6',agent:'M12 3v18M3 12h18M5.6 5.6l12.8 12.8M18.4 5.6 5.6 18.4',insights:'M4 21V11h4v10M10 21V3h4v18M16 21v-7h4v7',splits:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-4M16 3a4 4 0 0 1 0 8',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',food:'M4 3v7h6V3M7 3v18M17 3v18M17 3q5 3 0 9',shopping:'M5 7h14l2 14H3ZM8 7V5a4 4 0 0 1 8 0v2',transport:'M4 16V7a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v9ZM4 11h16M6 20v-4M18 20v-4M7 14h.01M17 14h.01',plus:'M12 5v14M5 12h14',arrow:'M5 12h14M13 6l6 6-6 6',check:'M4 12l5 5L20 6'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.ledger}"/></svg>`;
const cat=()=>'<img class="cat" src="neko-mascot.png" alt="Neko, the white lucky cat with orange tabby markings, aqua glasses, and a gold bell" decoding="async">';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
let page='home',filter='all',query='',reducedMotion=false,speaking=false;
const messages=[];
const entries=[{id:1,merchant:'Blue Tokai',category:'Food',amount:320,bank:'ICICI',time:'Today, 10:24',icon:'food',draft:false},{id:2,merchant:'Metro recharge',category:'Transport',amount:500,bank:'IDFC FIRST',time:'Today, 09:10',icon:'transport',draft:false},{id:3,merchant:'UPI payment',category:'Needs review',amount:850,bank:'AU',time:'Yesterday, 20:45',icon:'ledger',draft:true},{id:4,merchant:'Amazon',category:'Shopping',amount:1299,bank:'ICICI',time:'Yesterday, 14:22',icon:'shopping',draft:false},{id:5,merchant:'Salary',category:'Income',amount:45000,bank:'ICICI',time:'1 Oct, 10:00',icon:'ledger',credit:true,draft:false}];
const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pill=text=>`<span class="pill"><span class="dot"></span>${text}</span>`;
const header=(title,sub='')=>`<header class="topbar"><div>${sub?`<p>${sub}</p>`:''}<h2>${title}</h2></div><button class="icon-button" data-page="settings" aria-label="Open settings">${icon('settings')}</button></header>`;
const sample='<div class="sample-label">Sample data · design preview only</div>';
const mascotStage=()=>`<div class="mascot-stage${speaking?' speaking':''}"><span class="mascot-shadow" aria-hidden="true"></span>${cat()}</div>`;
const row=e=>`<button class="transaction" data-entry="${e.id}"><span class="tx-icon">${icon(e.icon)}</span><span class="tx-copy"><strong>${escape(e.merchant)}</strong><small>${e.bank} · ${e.draft?'Draft':e.category} · ${e.time}</small></span><span class="tx-amount ${e.credit?'credit':''}">${e.credit?'+':'−'}${money(e.amount)}</span></button>`;

function home(){
  const opening=messages.length?messages.map(m=>`<div class="chat-bubble ${m.from==='you'?'user':'neko'}${m.typing?' typing':''}${m.animate?' bubble-pop':''}">${m.from==='neko'?'<small>NEKO</small>':''}${m.typing?'<span class="typing-dots" role="status" aria-label="Neko is replying"><i></i><i></i><i></i></span>':escape(m.text)}</div>`).join(''):`<div class="chat-bubble neko welcome-bubble bubble-pop"><small>NEKO</small>Hi Demo User. Want to look at a payment, a budget, or anything else on your mind?</div><div class="suggestions"><button class="outline" data-prompt="What should I review?">What should I review?</button><button class="outline" data-prompt="How are my budgets?">How are my budgets?</button><button class="outline" data-prompt="Summarize this month">Summarize this month</button></div>`;
  return `<div class="agent-home">${header('Neko','Listening for bank SMS')}<div class="agent-status">${pill('Here when you need me')}</div>${mascotStage()}<div id="chat-thread" class="chat-thread" role="log" aria-live="polite" aria-relevant="additions text">${opening}</div><form id="home-chat-form" class="compose" aria-busy="${speaking}"><input id="home-question" placeholder="Ask Neko anything…" aria-label="Ask Neko" required maxlength="2000" ${speaking?'disabled':''}><button type="submit" aria-label="Send to Neko" ${speaking?'disabled':''}>${icon('arrow')}</button></form><p class="preview-disclaimer">Preview chat is sample-only. Nothing is sent to an AI or account.</p>${sample}</div>`;
}
function ledger(){return `${header('Your ledger','Every entry has a story.')}<input id="search" type="search" placeholder="Search merchant or bank" aria-label="Search transactions" value="${escape(query)}"><div class="filters"><button data-filter="all" class="${filter==='all'?'selected':''}">All</button><button data-filter="draft" class="${filter==='draft'?'selected':''}">Needs review</button><button data-filter="credit" class="${filter==='credit'?'selected':''}">Income</button></div><div id="entries">${filteredRows()}</div><button class="outline full" id="export-csv" style="margin-top:22px">Export sample CSV</button>${sample}`}
function filteredRows(){const found=entries.filter(e=>(filter==='all'||filter==='draft'&&e.draft||filter==='credit'&&e.credit)&&(e.merchant+' '+e.bank).toLowerCase().includes(query.toLowerCase()));return found.length?found.map(row).join(''):'<p class="empty">No matching entries. Try another merchant or bank.</p>'}
function activity(){return `${header('Neko’s check-ins','Small things, handled thoughtfully.')}<section class="panel"><div class="budget-row"><strong>Evening money check-in</strong>${pill('8 pm IST')}</div><p class="hint">Review new drafts and flag anything that needs your context.</p><div class="setting-row"><div>Daily responsibility<p>Runs on the backend when the app is closed.</p></div><button class="toggle" role="switch" aria-label="Evening check-in" aria-checked="true" id="activity-toggle"></button></div></section><h3>Recent activity</h3><section class="panel"><p class="hint">No new check-ins yet. When Neko notices something, it will show up here with a link to the right transaction.</p></section>${sample}`}
function insights(){return `${header('A clearer picture','October 2026')}<section class="panel"><small>Confirmed spending</small><div class="large-amount">${money(12740)}</div><p class="hint">Drafts, failed payments, and matched transfers are excluded.</p></section><h3>Where it went</h3><section class="panel">${[['Food',4200,6000],['Shopping',3800,5000],['Transport',2200,4000],['Bills',2540,5000]].map(([n,v,max])=>`<div class="budget-row"><span>${n}</span><strong>${money(v)} <span class="muted">/ ${money(max)}</span></strong></div><div class="bar"><span style="width:${v/max*100}%"></span></div>`).join('')}</section><section class="panel"><h3>One useful thought</h3><p class="hint">Your food budget has ${money(1800)} left in this sample month. Neko can help you check in before it gets tight.</p><button class="quiet" data-page="home">Talk it through with Neko</button></section>${sample}`}
function splits(){return `${header('Good company','Keep shared money simple.')}<section class="panel"><div class="group"><span class="tx-icon">${icon('splits')}</span><div><strong>Your Splitwise</strong><p>Connected directly on your phone</p></div>${pill('Demo')}</div><p class="hint">Your Splitwise key stays encrypted on Android. The preview does not connect to Splitwise.</p></section><div class="section-head"><h3>Your groups</h3><button class="quiet" id="new-group">New group</button></div>${[['Weekend people','4 friends · INR'],['Flatmates','3 friends · INR']].map(([n,s])=>`<section class="panel group"><span class="tx-icon">${icon('splits')}</span><div><strong>${n}</strong><p>${s}</p></div><button class="icon-button" data-group="${n}" aria-label="Open ${n}">${icon('arrow')}</button></section>`).join('')}<h3>Recent shared expense</h3><section class="panel"><div class="budget-row"><span>Dinner together</span><strong>${money(2400)}</strong></div><p class="hint">Weekend people · Paid by you · 4 equal shares</p><button class="quiet" id="split-review">Review the split</button></section>${sample}`}
function settings(){return `${header('Make Neko yours')}<section class="panel"><h3>Appearance</h3><button class="outline full" id="inner-theme">Switch to ${document.documentElement.dataset.theme==='dark'?'light':'dark'} mode</button><div class="setting-row"><div>Reduce motion<p>Keep the cat still</p></div><button class="toggle" role="switch" aria-label="Reduce motion" aria-checked="${reducedMotion}" id="motion"></button></div></section><section class="panel"><h3>Agent connection</h3>${pill('Fly.io + Neon')}<p class="hint">The Android app stores your OpenRouter key on its backend after you connect it. This preview never reads keys or connects to your accounts.</p><button class="outline full" data-page="byok">OpenRouter key setup</button><div class="setting-row"><div>Model<p>MiMo V2.6 Pro · paid model</p></div>${pill('On device')}</div></section><section class="panel"><h3>Transaction capture</h3><p class="hint">ICICI, IDFC FIRST, and AU SMS is parsed on-device. Android may delay background work; tapping a notification opens the relevant entry.</p></section><button class="outline full" data-page="login">Preview the login screen</button>${sample}`}
function login(){return `<section class="welcome">${cat()}<h2>Make room for clarity.</h2><p class="hint">Your money, your Neko.<br>A personal agent that keeps you in control.</p></section><div class="form-fields"><div><label for="email">Email</label><input id="email" type="email" placeholder="you@example.com" autocomplete="off"></div><div><label for="password">Neko password</label><input id="password" type="password" placeholder="Preview only — don’t enter credentials" disabled></div></div><button class="full" data-page="byok">Preview key setup</button><button class="quiet full" data-page="home">Try local features first</button><p class="hint">In Android, sign-in connects to your Fly.io backend. Neko never needs bank credentials.</p>${sample}`}
function byok(){return `<section class="welcome">${cat()}<h2>Bring your own key.</h2><p class="hint">Connect OpenRouter.<br>Choose the model Neko uses.</p></section><section class="panel"><h3>MiMo V2.6 Pro</h3><p class="hint">A capable paid model for thoughtful answers, summaries, and draft categorization.</p></section><div class="form-fields"><div><label for="model-key">Your OpenRouter key</label><input id="model-key" type="password" placeholder="Paste in Android, not this preview" disabled></div></div><p class="hint">The Android app sends the key over HTTPS to encrypted backend storage. It is never bundled in the APK. Set a spending limit on OpenRouter.</p><button class="full" data-page="home">Back to Neko</button>${sample}`}
const screens={home,ledger,agent:activity,insights,splits,settings,login,byok};
function render(){document.body.classList.toggle('reduce-motion',reducedMotion);const screen=$('#screen');screen.innerHTML=screens[page]();screen.classList.toggle('agent-preview',page==='home');$('#screen-select').value=page;$('#nav').style.display=['login','byok'].includes(page)?'none':'grid';$('#nav').innerHTML=['home','ledger','agent','insights','splits'].map(p=>`<button data-page="${p}" class="${page===p?'active':''}" ${page===p?'aria-current="page"':''}>${icon(p)}<span>${{home:'Neko',ledger:'Ledger',agent:'Activity',insights:'Insights',splits:'Splits'}[p]}</span></button>`).join('');}
function navigate(next){page=next;render()}
function theme(){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;$('#theme-toggle').textContent=`Switch to ${next==='dark'?'light':'dark'}`;render()}
function modal(html){$('#detail-content').innerHTML=html;$('#detail').showModal()}
$('#screen-select').addEventListener('change',e=>navigate(e.target.value));$('#theme-toggle').addEventListener('click',theme);$('#close-dialog').addEventListener('click',()=>$('#detail').close());
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){navigate(b.dataset.page);return}if(b.dataset.prompt){$('#home-question').value=b.dataset.prompt;$('#home-question').focus();return}if(b.dataset.filter){filter=b.dataset.filter;render();return}if(b.dataset.entry){const t=entries.find(t=>t.id===Number(b.dataset.entry));modal(`<h2>${escape(t.merchant)}</h2><div class="large-amount">${money(t.amount)}</div><p class="hint">${t.bank} · ${t.time}<br>Category: ${t.category}<br>Status: ${t.draft?'Draft — needs confirmation':'Confirmed'}</p>${t.draft?'<button class="full" id="confirm-demo">Confirm in this sample</button>':''}<p class="hint">This affects sample data only.</p>`);return}if(b.id==='confirm-demo'){const t=entries.find(t=>t.draft);t.draft=false;t.category='Food';$('#detail').close();render();return}if(b.id==='inner-theme')theme();if(b.id==='motion'){reducedMotion=!reducedMotion;b.setAttribute('aria-checked',String(reducedMotion));document.querySelectorAll('.paw').forEach(p=>p.style.animation=reducedMotion?'none':'');return}if(b.id==='activity-toggle'){b.setAttribute('aria-checked',String(b.getAttribute('aria-checked')!=='true'));return}if(b.id==='new-group'||b.dataset.group)modal('<h2>Shared money, made clear.</h2><p>Create or join a Neko group in Android. Everyone sees a clear record of their share.</p><p class="hint">Groups in this preview are samples. It will not post to Splitwise.</p>');if(b.id==='split-review')modal('<h2>Dinner together</h2><div class="large-amount">₹2,400</div><p>4 friends · ₹600 each</p><p class="hint">The Android app asks you before posting a shared expense. This preview does not post to Splitwise.</p>');if(b.id==='export-csv'){const csv='merchant,amount_inr,bank,review\n'+entries.map(t=>[t.merchant,t.amount,t.bank,t.draft?'DRAFT':'CONFIRMED'].join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='neko-sample.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;$('#entries').innerHTML=filteredRows()}});
document.addEventListener('submit',e=>{if(!['home-chat-form','chat-form'].includes(e.target.id))return;e.preventDefault();const input=e.target.querySelector('input'),q=input.value.trim();if(!q||speaking)return;messages.push({from:'you',text:q,animate:true});const pending={from:'neko',text:'',typing:true,animate:true};messages.push(pending);speaking=true;render();window.setTimeout(()=>{pending.typing=false;pending.text='This web preview is sample-only. In the Android app, I’ll use the ledger you choose to share and ask before making a change.';speaking=false;if(page==='home'){render();document.querySelector('#chat-thread')?.scrollTo({top:99999,behavior:'smooth'})}window.setTimeout(()=>{pending.animate=false;if(page==='home')render()},360)},850)});
document.addEventListener('click',e=>{if(e.target.closest('#motion'))document.body.classList.toggle('reduce-motion',reducedMotion)});
render();
